style: add shfmt and black to pre-commit, reformat

diff --git a/iam-policy-delete b/iam-policy-delete
--- a/iam-policy-delete
+++ b/iam-policy-delete
@@ -3,13 +3,13 @@
 set -euo pipefail
 
 die() {
-    echo "$*" 1>&2
-    exit 1
+  echo "$*" 1>&2
+  exit 1
 }
 
 POLICY=${1:-}
 if [[ -z $POLICY ]]; then
-    die "Error, please provide a policy to delete"
+  die "Error, please provide a policy to delete"
 fi
 
 aws iam list-policies | jq -r '.Policies[] | select(.PolicyName == "'$POLICY'").Arn' | xargs -r -n1 aws iam delete-policy --policy-arn
diff --git a/sshi b/sshi
--- a/sshi
+++ b/sshi
@@ -2,19 +2,19 @@
 set -euo pipefail
 
 die() {
-    echo "$*" 1>&2
-    exit 1
+  echo "$*" 1>&2
+  exit 1
 }
 
 ID="${1:-}"
 if [[ -z $ID ]]; then
-    die "please provide the instance ID, for example 'i-0a393a33dbaa0e1d7'"
+  die "please provide the instance ID, for example 'i-0a393a33dbaa0e1d7'"
 fi
 
 IP=$(aws ec2 describe-instances --instance-ids "$ID" | jq '.Reservations[0].Instances[0].PublicDnsName' -r)
 
 if [[ -z $IP ]]; then
-    die "Error, instalce [$ID] doesnt have a PublicDnsName"
+  die "Error, instalce [$ID] doesnt have a PublicDnsName"
 fi
 
 ssh -oStrictHostKeyChecking=no "$IP"
